require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '12.4'

target 'Mallard' do
  config = use_native_modules!

    use_react_native!(
      :path => config[:reactNativePath],
      # to enable hermes on iOS, change `false` to `true` and then install pods
      :hermes_enabled => false
    )
    pod 'react-native-config', :path => '../node_modules/react-native-config'
      #   https://github.com/luggit/react-native-config/issues/187
    pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

    pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

    pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

    pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
    post_install do |installer|
     react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-config'
        phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
        phase.shell_script = "cd ../../"\
        " && RNC_ROOT=./node_modules/react-native-config/"\
        " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
        " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"\

        target.build_phases << phase
        target.build_phases.move(phase,0)
      end
    end
   end

  # permisions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  target 'MallardTests' do
    inherit! :complete
    # Pods for testing
  end


  


end
