platform :ios, '12.4'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAnalyticsWithoutAdIdSupport = true

install! 'cocoapods', :deterministic_uuids => false

target 'Mallard' do
    config = use_native_modules!

     # Flags change depending on the env values.
    flags = get_default_flags()

    use_react_native!(
        :path => config[:reactNativePath],
         # Hermes is now enabled by default. Disable by setting this flag to false.
         # Upcoming versions of React Native may rely on get_default_flags(), but
         # we make it explicit here to aid in the React Native upgrade process.
         :hermes_enabled => true,
        :fabric_enabled => flags[:fabric_enabled],
        :flipper_configuration => FlipperConfiguration.disabled,
        # An absolute path to your application root.
        :app_path => "#{Pod::Config.instance.installation_root}/.."
        )
  # Pods for Mallard

  pod 'react-native-config', :path => '../node_modules/react-native-config'
#   https://github.com/luggit/react-native-config/issues/187
    pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

    pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  # https://mobiledevtutorials.com/how-to-fix-swift-pods-cannot-yet-be-integrated-as-static-libraries-firebasecoreinternal-library/?utm_content=cmp-true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  # permisions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  target 'MallardTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
      )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

end
