# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# before_all do
#  ensure_git_branch
#  ensure_git_status_clean
#  git_pull
# end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    create_keychain(
      name: "CI",
      password: ENV["FASTLANE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    # Get the distribution certificate
    sync_code_signing(
      type: "appstore",
      readonly: true,
      git_url: "https://github.com/guardian/code-signing.git",
      keychain_name: "CI",
      keychain_password: ENV["FASTLANE_PASSWORD"]
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/Mallard.xcodeproj",
    )

    increment_build_number(
      xcodeproj: "ios/Mallard.xcodeproj",
      build_number: latest_testflight_build_number.to_i + 1
    )

    ENV["SPACESHIP_SKIP_2FA_UPGRADE"] = "1"
    ENV["FASTLANE_DISABLE_OUTPUT_FORMAT"] = "true"
    ENV["FASTLANE_HIDE_TIMESTAMP"] = "true"
    puts("::set-output name=buildnumber::#{latest_testflight_build_number.to_i + 1}")
    ENV["FASTLANE_DISABLE_OUTPUT_FORMAT"] = "false"
    ENV["FASTLANE_HIDE_TIMESTAMP"] = "false"


    build_app(
      scheme: "Mallard",
      workspace: "ios/Mallard.xcworkspace",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        exportOptionsPlist: "exports-plists/release.plist"
      }
    )
    upload_to_testflight(
        distribute_external: true,
        notify_external_testers: true,
        skip_waiting_for_build_processing: true,
        changelog: "Thanks for testing the app! We've made some improvements",
        groups: ["GNM"],
        demo_account_required: false,
        beta_app_review_info: {
            contact_email: "Editions.coreteam@guardian.co.uk",
            contact_first_name: "Editions",
            contact_last_name: "Team",
            contact_phone: "03303336767"
    },
    )
  end
end

platform :android do
  desc "Push a new internal testing build to Google Play"
  lane :beta do
    gradle(task: 'assemble',
           build_type: 'Release',
           project_dir: 'android/'
    )
    supply(
      track: 'internal',
      package_name: 'com.guardian.editions'
    )
  end
end

platform :android do
  desc "Push a new production build to Google Play's release track"
  lane :release_to_production do
    gradle(task: 'assemble',
           build_type: 'Release',
           project_dir: 'android/'
    )
    supply(
      track: 'production',
      package_name: 'com.guardian.editions'
    )
  end
end
