# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# before_all do
#  ensure_git_branch
#  ensure_git_status_clean
#  git_pull
# end

version = JSON.parse(open("../src/version-info.json").read)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
      xcodeproj: "ios/Mallard.xcodeproj",
      build_number: latest_testflight_build_number + 1
    )
    build_app(
      scheme: "Mallard",
      project: "ios/Mallard.xcodeproj",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        exportOptionsPlist: "exports-plists/release.plist"
      }
    )
    upload_to_testflight(
        distribute_external: false,
        notify_external_testers: false,
        changelog: "Thanks for testing the app! We've done some improvements",
        groups: ["GNM"]
    )
  end
end

platform :android do
  desc "Push a new internal testing build to Google Play"
  lane :beta do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble',
           build_type: 'Release',
           project_dir: 'android/',
           properties: {
               "versionName" => version["version"]
           }
    )
    supply(
      track: 'internal',
      package_name: 'com.guardian.editions'
    )
  end
end
