module.exports = {
    name: 'Quick crossword No 15,346',
    type: 'quick',
    number: 15346,
    date: '2019-07-15T00:00:00Z',
    dimensions: { cols: 13, rows: 13 },
    entries: [
        {
            id: '1-across',
            number: 1,
            humanNumber: '1',
            direction: 'across',
            position: { x: 1, y: 0 },
            separatorLocations: {},
            length: 11,
            clue: 'Peanut scale (anag) — put in concise form (11)',
            group: ['1-across'],
            solution: 'ENCAPSULATE',
            format: '11',
        },
        {
            id: '9-across',
            number: 9,
            humanNumber: '9',
            direction: 'across',
            position: { x: 0, y: 2 },
            separatorLocations: { ',': [2, 5] },
            length: 9,
            clue: 'For the most part (2,3,4)',
            group: ['9-across'],
            solution: 'INTHEMAIN',
            format: '2,3,4',
        },
        {
            id: '10-across',
            number: 10,
            humanNumber: '10',
            direction: 'across',
            position: { x: 10, y: 2 },
            separatorLocations: {},
            length: 3,
            clue: 'Type of bread (3)',
            group: ['10-across'],
            solution: 'RYE',
            format: '3',
        },
        {
            id: '11-across',
            number: 11,
            humanNumber: '11',
            direction: 'across',
            position: { x: 0, y: 4 },
            separatorLocations: {},
            length: 5,
            clue: 'Dog (5)',
            group: ['11-across'],
            solution: 'HOUND',
            format: '5',
        },
        {
            id: '13-across',
            number: 13,
            humanNumber: '13',
            direction: 'across',
            position: { x: 6, y: 4 },
            separatorLocations: {},
            length: 7,
            clue: 'Rich tea, for example (7)',
            group: ['13-across'],
            solution: 'BISCUIT',
            format: '7',
        },
        {
            id: '14-across',
            number: 14,
            humanNumber: '14',
            direction: 'across',
            position: { x: 0, y: 6 },
            separatorLocations: {},
            length: 6,
            clue: 'Hinder (6)',
            group: ['14-across'],
            solution: 'IMPEDE',
            format: '6',
        },
        {
            id: '15-across',
            number: 15,
            humanNumber: '15',
            direction: 'across',
            position: { x: 7, y: 6 },
            separatorLocations: {},
            length: 6,
            clue: 'Goblin, elf or imp (6)',
            group: ['15-across'],
            solution: 'SPRITE',
            format: '6',
        },
        {
            id: '18-across',
            number: 18,
            humanNumber: '18',
            direction: 'across',
            position: { x: 0, y: 8 },
            separatorLocations: {},
            length: 7,
            clue: 'Largest living primate (7)',
            group: ['18-across'],
            solution: 'GORILLA',
            format: '7',
        },
        {
            id: '20-across',
            number: 20,
            humanNumber: '20',
            direction: 'across',
            position: { x: 8, y: 8 },
            separatorLocations: {},
            length: 5,
            clue: 'Shafted weapon for throwing or thrusting (5)',
            group: ['20-across'],
            solution: 'SPEAR',
            format: '5',
        },
        {
            id: '21-across',
            number: 21,
            humanNumber: '21',
            direction: 'across',
            position: { x: 0, y: 10 },
            separatorLocations: {},
            length: 3,
            clue: 'Tax-free savings account (3)',
            group: ['21-across'],
            solution: 'ISA',
            format: '3',
        },
        {
            id: '22-across',
            number: 22,
            humanNumber: '22',
            direction: 'across',
            position: { x: 4, y: 10 },
            separatorLocations: {},
            length: 9,
            clue: 'Newly coined word (9)',
            group: ['22-across'],
            solution: 'NEOLOGISM',
            format: '9',
        },
        {
            id: '24-across',
            number: 24,
            humanNumber: '24',
            direction: 'across',
            position: { x: 1, y: 12 },
            separatorLocations: {},
            length: 11,
            clue: 'Famous people (11)',
            group: ['24-across'],
            solution: 'CELEBRITIES',
            format: '11',
        },
        {
            id: '2-down',
            number: 2,
            humanNumber: '2',
            direction: 'down',
            position: { x: 2, y: 0 },
            separatorLocations: {},
            length: 3,
            clue: 'Muggins (3)',
            group: ['2-down'],
            solution: 'NIT',
            format: '3',
        },
        {
            id: '3-down',
            number: 3,
            humanNumber: '3',
            direction: 'down',
            position: { x: 4, y: 0 },
            separatorLocations: {},
            length: 7,
            clue: 'Rectified (7)',
            group: ['3-down'],
            solution: 'AMENDED',
            format: '7',
        },
        {
            id: '4-down',
            number: 4,
            humanNumber: '4',
            direction: 'down',
            position: { x: 6, y: 0 },
            separatorLocations: {},
            length: 6,
            clue: 'Despicable — BBC, say (anag) (6)',
            group: ['4-down'],
            solution: 'SCABBY',
            format: '6',
        },
        {
            id: '5-down',
            number: 5,
            humanNumber: '5',
            direction: 'down',
            position: { x: 8, y: 0 },
            separatorLocations: {},
            length: 5,
            clue: 'Respiratory organs (5)',
            group: ['5-down'],
            solution: 'LUNGS',
            format: '5',
        },
        {
            id: '6-down',
            number: 6,
            humanNumber: '6',
            direction: 'down',
            position: { x: 10, y: 0 },
            separatorLocations: {},
            length: 9,
            clue: 'Greenish blue (9)',
            group: ['6-down'],
            solution: 'TURQUOISE',
            format: '9',
        },
        {
            id: '7-down',
            number: 7,
            humanNumber: '7',
            direction: 'down',
            position: { x: 0, y: 1 },
            separatorLocations: { ',': [8] },
            length: 11,
            clue: 'In good physical condition (8,3)',
            group: ['7-down'],
            solution: 'FIGHTINGFIT',
            format: '8,3',
        },
        {
            id: '8-down',
            number: 8,
            humanNumber: '8',
            direction: 'down',
            position: { x: 12, y: 1 },
            separatorLocations: {},
            length: 11,
            clue: 'Timpani (11)',
            group: ['8-down'],
            solution: 'KETTLEDRUMS',
            format: '11',
        },
        {
            id: '12-down',
            number: 12,
            humanNumber: '12',
            direction: 'down',
            position: { x: 2, y: 4 },
            separatorLocations: { ',': [5] },
            length: 9,
            clue: 'Capital letters (5,4)',
            group: ['12-down'],
            solution: 'UPPERCASE',
            format: '5,4',
        },
        {
            id: '16-down',
            number: 16,
            humanNumber: '16',
            direction: 'down',
            position: { x: 8, y: 6 },
            separatorLocations: { ',': [4] },
            length: 7,
            clue: 'Faint — finish military training (4,3)',
            group: ['16-down'],
            solution: 'PASSOUT',
            format: '4,3',
        },
        {
            id: '17-down',
            number: 17,
            humanNumber: '17',
            direction: 'down',
            position: { x: 6, y: 7 },
            separatorLocations: {},
            length: 6,
            clue: 'Toil (6)',
            group: ['17-down'],
            solution: 'LABOUR',
            format: '6',
        },
        {
            id: '19-down',
            number: 19,
            humanNumber: '19',
            direction: 'down',
            position: { x: 4, y: 8 },
            separatorLocations: {},
            length: 5,
            clue: 'Shafted weapon used on horseback (5)',
            group: ['19-down'],
            solution: 'LANCE',
            format: '5',
        },
        {
            id: '23-down',
            number: 23,
            humanNumber: '23',
            direction: 'down',
            position: { x: 10, y: 10 },
            separatorLocations: {},
            length: 3,
            clue: 'Choler (3)',
            group: ['23-down'],
            solution: 'IRE',
            format: '3',
        },
    ],
    solutionAvailable: true,
    hasNumbers: true,
    randomCluesOrdering: false,
    pdf: 'https://crosswords-static.guim.co.uk/gdn.quick.20190715.pdf',
    dateSolutionAvailable: '2019-07-14T23:00:00Z',
}
