#!/usr/bin/env bash

set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT_DIR="${DIR}/.."

mkdir $ROOT_DIR/zipfiles

# Create zip files of the different dist directories
(
  cd "$ROOT_DIR/projects/backend/dist/"
  zip -r "$ROOT_DIR/zipfiles/editions-backend.zip" .
  cd "$ROOT_DIR/projects/archiver/dist/"
  zip -r "$ROOT_DIR/zipfiles/editions-archiver.zip" .
  cd "$ROOT_DIR/projects/logging/dist/"
  zip -r "$ROOT_DIR/zipfiles/editions-logging.zip" .
)