#!/bin/bash
# A bash script that calls gmake or make as available on your system
USE_GMAKE=$(which gmake)
UNAME=$(uname)
if [ -n "$USE_GMAKE" ]; then
    exec gmake "$@"
else
    if [ "$UNAME" == "Darwin" ]; then
        echo "ERROR: make on macOS is not sophisticated enough for our needs, please 'brew install make' to get gmake"
        exit 1
    fi
    exec make "$@"
fi