AWSTemplateFormatVersion: '2010-09-09'

Parameters:
    Stage:
        Type: String
        AllowedValues:
            - prod
            - code
        ConstraintDescription: must be a valid stage.

Resources:
    ProofBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub editions-proofed-${Stage}
            LifecycleConfiguration:
                Rules:
                    - Id: DeleteContentAfter1YearUS
                      ExpirationInDays: 365
                      Status: Enabled
                      Prefix: 'american-edition'
                    - Id: DeleteContentAfter1YearAU
                      ExpirationInDays: 365
                      Status: Enabled
                      Prefix: 'australian-edition'
                    - Id: DeleteContentAfter1YearUK
                      ExpirationInDays: 365
                      Status: Enabled
                      Prefix: 'daily-edition'

    PublishedBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub editions-published-${Stage}
            LifecycleConfiguration:
                Rules:
                    - Id: DeleteContentAfter1YearUS
                      ExpirationInDays: 365
                      Status: Enabled
                      Prefix: 'american-edition'
                    - Id: DeleteContentAfter1YearAU
                      ExpirationInDays: 365
                      Status: Enabled
                      Prefix: 'australian-edition'
                    - Id: DeleteContentAfter1YearUK
                      ExpirationInDays: 365
                      Status: Enabled
                      Prefix: 'daily-edition'
