AWSTemplateFormatVersion: '2010-09-09'

Parameters:
    Stage:
        Type: String
        AllowedValues:
            - prod
            - code
        ConstraintDescription: must be a valid stage.

Resources:
    ProofBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub editions-proofed-${Stage}
            LifecycleConfiguration:
                Rules:
                    - Id: DeleteContentAfter1Year
                      ExpirationInDays: 365
                      Status: 'Enabled'

    PublishedBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub editions-published-${Stage}
            LifecycleConfiguration:
                Rules:
                    - Id: DeleteContentAfter1Year
                      ExpirationInDays: 365
                      Status: 'Enabled'
