export const routeNames = {
    Issue: 'Issue',
    Article: 'Article',
    IssueList: 'IssueList',
    Settings: 'Settings',
    Endpoints: 'Endpoints',
    Edition: 'Edition',
    GdprConsent: 'GdprConsent',
    PrivacyPolicy: 'PrivacyPolicy',
    TermsAndConditions: 'TermsAndConditions',
    Help: 'Help',
    ManageEditions: 'ManageEditions',
    ManageEditionsSettings: 'ManageEditionsSettings',
    Credits: 'Credits',
    FAQ: 'FAQ',
    AlreadySubscribed: 'AlreadySubscribed',
    SubscriptionDetails: 'SubscriptionDetails',
    SignIn: 'SignIn',
    CasSignIn: 'CasSignIn',
    WeatherGeolocationConsent: 'WeatherGeolocationConsent',
    onboarding: {
        OnboardingStart: 'OnboardingStart',
        OnboardingConsent: 'OnboardingConsent',
        OnboardingConsentInline: 'OnboardingConsentInline',
        PrivacyPolicyInline: 'PrivacyPolicyInline',
    },
}
