name: android-release

on:
  workflow_dispatch:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - uses: actions/setup-node@v3
      with:
        node-version-file: 'projects/Mallard/.nvmrc'

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        bundler-cache: true

    - name: inject credentials
      run: |
        echo -e "\n\n${{ secrets.ANDROID_GRADLE_PROPERTIES }}" >> projects/Mallard/android/gradle.properties
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > projects/Mallard/android/app/editions-release-2023.keystore

    # For legacy reason we are adding last version code pre-team city (14001358) from Play Store
    # We are adding 60 because that was the last build number to run in TeamCity
    - name: set build number
      run: |
        echo "BUILD_NUMBER=$(($NUM+14001358+60))" >> "$GITHUB_ENV"
      env:
        NUM: ${{ github.run_number }}

    - name: install
      run: |
          make install

    - name: validate
      run: make validate-Mallard

    - name: Build APK
      id: build_app
      run: |
        ./build_apk.sh RELEASE
        pwd
        ls
        ls projects/Mallard/android/app/build/outputs/apk/release/
      env:
        ID_ACCESS_TOKEN: ${{ secrets.ID_ACCESS_TOKEN }}
        ID_API_URL: ${{ secrets.ID_API_URL }}
        LOGGING_API_KEY: ${{ secrets.LOGGING_API_KEY }}
        ITUNES_CONNECT_SHARED_SECRET: ${{ secrets.ITUNES_CONNECT_SHARED_SECRET }}
        MEMBERS_DATA_API_URL: ${{ secrets.MEMBERS_DATA_API_URL }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_CLI_EXECUTABLE: ${{ secrets.SENTRY_CLI_EXECUTABLE }}
        SENTRY_DEFAULTS_ORG: ${{ secrets.SENTRY_DEFAULTS_ORG }}
        SENTRY_DEFAULTS_PROJECT: ${{ secrets.SENTRY_DEFAULTS_PROJECT }}
        SENTRY_DEFAULTS_URL: ${{ secrets.SENTRY_DEFAULTS_URL }}
        SENTRY_DSN_URL: ${{ secrets.SENTRY_DSN_URL }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        ANDROID_RELEASE_STREAM: 'RELEASE'
        USE_SANDBOX_IAP: 'true'
        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
        BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: internal-apks
        path: |
          projects/Mallard/android/app/build/outputs/apk/release/app-release.apk

    - name: tag release on github
      working-directory: script
      run: node make-release.js ${{ github.sha }} ${{ github.ref }} ${{ env.BUILD_NUMBER }} android
      env:
        REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
