name: android-beta

on:
  workflow_dispatch:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:

    #first attempt to add a version tag to a commit
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create Tag
      run: |
        git tag v1.0.actionsnouser
        git push origin v1.0.actionsnouser

