name: android-beta

on:
  workflow_dispatch:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:

    #first attempt to add a version tag to a commit
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'Julia'
        git config --global user.email 'Julia.Branke@guardian.co.uk'

    - name: Create Tag
      run: |
        git tag v1.0.juliatest
        git push origin v1.0.juliatest

