name: Snyk

on:
  push:
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: false
      ORG: guardian-mobile
      SKIP_NODE: false
      EXCLUDE: Mallard
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  androidscan:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: false
      ORG: guardian-mobile
      SKIP_NODE: false
      PROJECT_FILE: ./projects/Mallard/android/app/build.gradle
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
